server:
  port: 8080
  servlet:
    context-path: /board-service

spring:
  application:
    name: board-service

  datasource:
    username: myapp
    url: jdbc:postgresql://localhost:5432/boardservice
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show_sql: true
    properties:
      hibernate:
        format_sql: 'true'
        default_schema: myapp
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      client:
        config:
          tasksService:
            readTimeout: 5000
            connectTimeout: 5000
            loggerLevel: FULL

client:
  task:
    baseUrl: http://localhost:8001
