spring:
  profiles:
    active: ${PROFILE:local}
  application:
    name: board-service
    request-interceptor:
      threshold: 5000
      enabled: true
  cloud:
    openfeign:
      client:
        config:
          tasksService:
            readTimeout: 5000
            connectTimeout: 5000
            loggerLevel: FULL

