server:
  port: 8080
  servlet:
    context-path: /board-service

spring:
  application:
    name: board-service

  datasource:
    username: myapp
    url: jdbc:postgresql://localhost:5432/boardservice
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show_sql: true
    properties:
      hibernate:
        format_sql: 'true'
        default_schema: myapp
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false

endpoint:
  task:
    url: http://localhost:8001
