version: '3.8'

services:
  board-service:
    build:
      context: ../../
      dockerfile: ${PWD}/Dockerfile
    container_name: board_service
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=docker
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./target:/app

  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DB=boardservice
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network
    volumes:
      - ../database:/docker-entrypoint-initdb.d

  smockin:
    image: mgallina/smockin:2201
    container_name: smockin
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge